version: "3.8"

services:

  # Service Provider Instance
  provider-blockchain-connector-core:
    container_name: provider-blockchain-connector-core
    image: ocanades/blockchain-connector-core:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8081:8080"
    volumes:
      - ./provider-config.yml:/src/main/resources/integration-config.yml
    links:
      - provider-orionld-adapter
      - provider-dlt-adapter
    networks:
      - local_network

  provider-orionld-adapter:
    container_name: provider-orionld-adapter
    image: ocanades/orionld-adapter:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8082:8080"
    volumes:
      - ./provider-config.yml:/src/main/resources/custom-config.yml
    networks:
      - local_network

  provider-dlt-adapter:
    container_name: provider-dlt-adapter
    image: ocanades/dlt-adapter:1.0.0
    ports:
      - "8083:8080"
    networks:
      - local_network

  provider-orionld:
    container_name: provider-orionld
    image: fiware/orion-ld:latest
    command: "-dbhost provider-mongo -port 1026"
    ports:
      - "1027:1026"
    links:
      - provider-mongo
    networks:
      - local_network

  provider-mongo:
    container_name: provider-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - provider_data:/data/db
      - provider_db_config:/data/configdb
    networks:
      - local_network

  # Marketplace Instance
  marketplace-blockchain-connector-core:
    container_name: marketplace-blockchain-connector-core
    image: ocanades/blockchain-connector-core:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8091:8080"
    volumes:
      - ./marketplace-config.yml:/src/main/resources/integration-config.yml
    links:
      - marketplace-orionld-adapter
      - marketplace-dlt-adapter
    networks:
      - local_network

  marketplace-orionld-adapter:
    container_name: marketplace-orionld-adapter
    image: ocanades/orionld-adapter:1.0.0
    environment:
      - "SPRING_PROFILES_ACTIVE=dev"
    ports:
      - "8092:8080"
    volumes:
      - ./marketplace-config.yml:/src/main/resources/custom-config.yml
    networks:
      - local_network

  marketplace-dlt-adapter:
    container_name: marketplace-dlt-adapter
    image: ocanades/dlt-adapter:1.0.0
    ports:
      - "8093:8080"
    networks:
      - local_network

  marketplace-orionld:
    container_name: marketplace-orionld
    image: fiware/orion-ld:latest
    command: "-dbhost marketplace-mongo -port 1026"
    ports:
      - "1037:1026"
    links:
      - marketplace-mongo
    networks:
      - local_network

  marketplace-mongo:
    container_name: marketplace-mongo
    image: mongo:4.4
    command: "--nojournal"
    volumes:
      - marketplace_data:/data/db
      - marketplace_db_config:/data/configdb
    networks:
      - local_network

networks:
  local_network:
    driver: bridge

volumes:
  provider_data:
  provider_db_config:
  marketplace_data:
  marketplace_db_config: